LmP based Raspberry Pi3/4 support
PelionIoT/meta-mbed-edge pull request #47
Opened 2021-04-15 06:15 UTC by JanneKiiskila

LmP based (i.e. OSTree updates) based Raspberry Pi3/Pi4 support (draft).
Rebased on 2.3-RC5 (ordered reboot included).

2021-04-15 07:20 UTC, petedyerarm requested changes

2021-04-15 07:20 UTC, petedyerarm commented on recipes-connectivity/mbed-edge-core/mbed-edge-core-rpi3.bb
> -            file://arm_update_active_details.sh \
These files are for update client, so are not needed for FOTA.

2021-04-15 07:20 UTC, petedyerarm commented on recipes-connectivity/mbed-edge-core/mbed-edge-core-rpi3.bb
> +    install -m 755 "${SCRIPT_DIR}/yocto_generic/arm_update_active_details.sh" "${D}/wigwag/mbed"
These files are for update client, so are not needed for FOTA.

2021-04-15 07:45 UTC, kivaisan commented on recipes-connectivity/mbed-edge-core/mbed-edge-core-rpi3.bb
> +    install -m 755 "${SCRIPT_DIR}/yocto_generic/arm_update_active_details.sh" "${D}/wigwag/mbed"
So those should be removed from other targets (uz and imx8) too?

2021-04-15 07:46 UTC, kivaisan commented on recipes-connectivity/mbed-edge-core/mbed-edge-core-rpi3.bb
> +#COMPATIBLE_MACHINE = "raspberrypi3"
Remove commented line

2021-04-15 07:48 UTC, petedyerarm commented on recipes-connectivity/mbed-edge-core/mbed-edge-core-rpi3.bb
> +    install -m 755 "${SCRIPT_DIR}/yocto_generic/arm_update_active_details.sh" "${D}/wigwag/mbed"
Yes - and I should have done that, but didn't.

2021-04-15 07:49 UTC, kivaisan commented on recipes-connectivity/mbed-edge-core/mbed-edge-core-rpi3.bb
> +    install -m 755 "${SCRIPT_DIR}/yocto_generic/arm_update_active_details.sh" "${D}/wigwag/mbed"
Ok, I can make a PR to remove these from uz and imx8.

2021-04-15 08:08 UTC, JanneKiiskila commented on recipes-connectivity/mbed-edge-core/mbed-edge-core-rpi3.bb
> +    install -m 755 "${SCRIPT_DIR}/yocto_generic/arm_update_active_details.sh" "${D}/wigwag/mbed"
Removed them from this file.
On idea though - should we rename the rpi3 files to be just rpi, because they really aren't RPi3 specific?

2021-04-15 08:10 UTC, JanneKiiskila commented on recipes-connectivity/mbed-edge-core/mbed-edge-core-rpi3.bb
> +#COMPATIBLE_MACHINE = "raspberrypi3"
Done.

2021-04-15 08:21 UTC, JanneKiiskila commented on recipes-connectivity/mbed-edge-core/mbed-edge-core-rpi3.bb
> +    install -m 755 "${WORKDIR}/deploy_ostree_delta_update.sh" "${D}/wigwag/mbed"
This PR deletes those files already, interestingly it just passes the build even though those copy operations failed for sure? Not so nice, IMHO.

2021-04-15 09:29 UTC, kivaisan approved these changes
LGTM. I also tested Ostree FOTA update

2021-04-15 14:56 UTC, petedyerarm approved these changes

2021-04-15 17:38 UTC, ygoyal18 approved these changes
LGTM

2021-04-16 05:53 UTC, esajaa commented
I presume this drops the support for the old uc-hub update mechanism?

2021-04-16 05:54 UTC, esajaa approved these changes

2021-04-16 07:05 UTC, JanneKiiskila commented
Question is then who merges this in, @esajaa  @petedyerarm ?

2021-04-16 13:05 UTC, esajaa commented on recipes-connectivity/mbed-edge-core/mbed-edge-core-rpi3.bb
> +SCRIPT_DIR = "${WORKDIR}/git/lib/mbed-cloud-client/update-client-hub/modules/pal-linux/scripts"
Actually a bit late comment, but should this be removed? I don't think it's used anywhere, it was used to store the old update scripts

2021-04-16 22:53 UTC, JanneKiiskila commented on recipes-connectivity/mbed-edge-core/mbed-edge-core-rpi3.bb
> +SCRIPT_DIR = "${WORKDIR}/git/lib/mbed-cloud-client/update-client-hub/modules/pal-linux/scripts"
Removing it then.

2021-04-19 06:12 UTC, merged

2021-04-27 08:30 UTC, TapaniPuhakka commented on recipes-connectivity/mbed-edge-core/mbed-edge-core-rpi3.bb
> +COMPATIBLE_MACHINE = "^rpi$"
how this rpi matcher works? I understand machines are named raspberrypiX style and SOC_FAMILY is rpi but is that COMPATIBLE_MACHINE really matched agains SOC_FAMILY ?