Configure fota instead of patching
PelionIoT/meta-mbed-edge pull request #52
Opened 2021-04-20 11:01 UTC by kivaisan

Use defines to configure FOTA locations.

2021-04-20 11:23 UTC, kivaisan commented
@JanneKiiskila @esajaa @TapaniPuhakka @petedyerarm please review. I didn't do the upper level cmake here yet as it would require more testing on HWs I don't have.

2021-04-20 12:38 UTC, esajaa approved these changes
LGTM. Please create a jira ticket about the upper-level common configuration so that it isn't forgotten

2021-04-20 12:40 UTC, JanneKiiskila approved these changes

2021-04-20 12:47 UTC, kivaisan commented
IOTABBGW-189 created to implemtn common cmake configuration file.

2021-04-20 12:48 UTC, TapaniPuhakka commented on recipes-connectivity/mbed-edge-core/files/uz/target.cmake
> +add_definitions(
should these be under if (${FOTA_ENABLE}) (see line 28) ?

2021-04-20 12:50 UTC, TapaniPuhakka commented on recipes-connectivity/mbed-edge-core/files/imx8mmevk/target.cmake
> +add_definitions(
likely also should be flagged with fota enabled

2021-04-20 12:50 UTC, TapaniPuhakka commented on recipes-connectivity/mbed-edge-core/files/imx8mmevk/target.cmake
> +add_definitions(
as done with recipes-connectivity/mbed-edge-core/files/uz/target.cmake

2021-04-20 12:51 UTC, TapaniPuhakka commented on recipes-connectivity/mbed-edge-core/files/0003-fix_libwebsockets_nondebug.manual_patch
> -diff --git a/lib/libwebsockets/libwebsockets/CMakeLists.txt b/lib/libwebsockets/libwebsockets/CMakeLists.txt.txt
why was this removed?

2021-04-20 12:54 UTC, TapaniPuhakka commented
additionally I think we should have small change in the fota itself to have this configurable.
https://github.com/PelionIoT/meta-mbed-edge/blob/2ae666666d4afba6596e4f80c6a3048b45e92f32/recipes-connectivity/mbed-edge-core/files/0006-fota-callback.patch

2021-04-20 13:00 UTC, TapaniPuhakka commented
> additionally I think we should have small change in the fota itself to have this configurable.
> https://github.com/PelionIoT/meta-mbed-edge/blob/2ae666666d4afba6596e4f80c6a3048b45e92f32/recipes-connectivity/mbed-edge-core/files/0006-fota-callback.patch

actually can't even find fota/fota_install_callback.c . has that been removed already?

2021-04-20 13:02 UTC, petedyerarm commented
It is here:
https://github.com/PelionIoT/mbed-edge/blob/master/fota/fota_install_callback.c

2021-04-20 13:03 UTC, TapaniPuhakka commented
> It is here:
> https://github.com/PelionIoT/mbed-edge/blob/master/fota/fota_install_callback.c

ok so edge has different fota than mbed-cloud-client ?

2021-04-20 13:06 UTC, TapaniPuhakka commented
> > It is here:
> > https://github.com/PelionIoT/mbed-edge/blob/master/fota/fota_install_callback.c
> 
> ok so edge has different fota than mbed-cloud-client ?

ah ok, I see so for linux there needs to be something that implements that fota_app_on_install_candidate functions on the "app" side. No default implementation even provided. So client update has dependency to this single from from the mbed-edge and then this version of this file has dependency to our meta-mbed-edge to provide patch to modify that file.

2021-04-20 13:06 UTC, petedyerarm commented
mbed-edge contains mbed-cloud-client

https://github.com/PelionIoT/mbed-edge/tree/master/lib/mbed-cloud-client

2021-04-21 05:05 UTC, kivaisan commented on recipes-connectivity/mbed-edge-core/files/0003-fix_libwebsockets_nondebug.manual_patch
> -diff --git a/lib/libwebsockets/libwebsockets/CMakeLists.txt b/lib/libwebsockets/libwebsockets/CMakeLists.txt.txt
It was an unused file. There was still this old leftover comment for it: `# Temp fix for libwebsockets non-debug build` . I removed that as well.

2021-04-21 06:32 UTC, kivaisan commented on recipes-connectivity/mbed-edge-core/files/uz/target.cmake
> +add_definitions(
Fixed.

2021-04-21 06:32 UTC, kivaisan commented on recipes-connectivity/mbed-edge-core/files/imx8mmevk/target.cmake
> +add_definitions(
Fixed

2021-04-21 06:58 UTC, TapaniPuhakka commented on recipes-connectivity/mbed-edge-core/files/0003-fix_libwebsockets_nondebug.manual_patch
> -diff --git a/lib/libwebsockets/libwebsockets/CMakeLists.txt b/lib/libwebsockets/libwebsockets/CMakeLists.txt.txt
ok good

2021-04-29 08:44 UTC, kivaisan commented
Could this be merged?

2021-04-29 08:48 UTC, petedyerarm commented
It has conflicts that need to be resolved.

2021-04-29 08:48 UTC, JanneKiiskila commented
Rebase needed, we have a conflict @kivaisan .

2021-04-29 08:49 UTC, JanneKiiskila commented on recipes-connectivity/mbed-edge-core/mbed-edge-core.inc
> -           file://0003-fix_libwebsockets_nondebug.manual_patch \
Is this file (0003) really left out with some good reason? @kivaisan ?

2021-04-29 08:50 UTC, JanneKiiskila requested changes
Explanation needed why patch https://github.com/PelionIoT/meta-mbed-edge/blob/master/recipes-connectivity/mbed-edge-core/files/0003-fix_libwebsockets_nondebug.manual_patch is being left out. That has nothing to do with FOTA, AFAIK.

2021-04-29 08:51 UTC, petedyerarm commented on recipes-connectivity/mbed-edge-core/mbed-edge-core.inc
> -           file://0003-fix_libwebsockets_nondebug.manual_patch \
It no longer gets applied, but the reference to is was not removed. This is a tidy-up.

2021-04-29 08:51 UTC, kivaisan commented
> Explanation needed why patch https://github.com/PelionIoT/meta-mbed-edge/blob/master/recipes-connectivity/mbed-edge-core/files/0003-fix_libwebsockets_nondebug.manual_patch is being left out. That has nothing to do with FOTA, AFAIK.

Explained above. See https://github.com/PelionIoT/meta-mbed-edge/pull/52#discussion_r617202444

2021-04-29 08:53 UTC, kivaisan commented on recipes-connectivity/mbed-edge-core/mbed-edge-core.inc
> -           file://0003-fix_libwebsockets_nondebug.manual_patch \
Explained above. See https://github.com/PelionIoT/meta-mbed-edge/pull/52#discussion_r617202444

2021-04-29 08:58 UTC, kivaisan commented
Rebased.

2021-04-29 09:00 UTC, merged

2021-04-29 09:09 UTC, JanneKiiskila commented on recipes-connectivity/mbed-edge-core/files/0003-fix_libwebsockets_nondebug.manual_patch
> -diff --git a/lib/libwebsockets/libwebsockets/CMakeLists.txt b/lib/libwebsockets/libwebsockets/CMakeLists.txt.txt
And we confirmed that the debug build works even w/o this patch @kivaisan ?

2021-04-29 09:14 UTC, kivaisan commented on recipes-connectivity/mbed-edge-core/files/0003-fix_libwebsockets_nondebug.manual_patch
> -diff --git a/lib/libwebsockets/libwebsockets/CMakeLists.txt b/lib/libwebsockets/libwebsockets/CMakeLists.txt.txt
This was for **non-debug** builds and that is our default build type: https://github.com/PelionIoT/manifest-lmp-pelion-edge/blob/81c0646badb3f8f0132a14f78f604c978131d793/conf/local.conf#L80

I haven't tried debug builds recently.