Allow users to build Pelion Edge in BYOC_MODE
PelionIoT/meta-mbed-edge pull request #58
Opened 2021-06-04 19:48 UTC by ygoyal18

Adding python package recipes which are not avaiable in the default
openembedded/meta-python layer

2021-06-04 21:50 UTC, ryannowarm reviewed
Not a bad idea!  Although if this is a dev tool, is this opening up our old "is this a development platform" can of worms?  Should we instead document how to install/configure edge-tool on the developer's workstation and they can do the conversion there?

2021-06-07 05:53 UTC, esajaa requested changes
Small change and a clarifying question, mostly looks good to go

2021-06-07 05:53 UTC, esajaa commented on recipes-connectivity/edge-tool/edge-tool_0.2.0.bb
> +SRC_URI = "git://github.com/ARMmbed/mbed-edge.git"
PelionIoT as org, not ARMmbed

2021-06-07 05:53 UTC, esajaa commented on recipes-connectivity/edge-tool/edge-tool_0.2.0.bb
> +DESCRIPTION = "Tool to convert the development certificate to CBOR formatted object"
What's the reasoning behind version number 0.2.0?

2021-06-07 14:42 UTC, petedyerarm commented
Would we need to remove this at a later date for production images (as part of a general process to reduce the size of the image)?  If so then Ryan's suggestion of running it on the host and transferring the CBOR file to the device seems a better approach.

2021-06-07 17:31 UTC, ygoyal18 commented on recipes-connectivity/edge-tool/edge-tool_0.2.0.bb
> +SRC_URI = "git://github.com/ARMmbed/mbed-edge.git"
Done

2021-06-08 07:38 UTC, petedyerarm approved these changes
LGTM

2021-06-08 16:03 UTC, merged