Create and publish generic PE builds with BYOC_MODE
PelionIoT/meta-mbed-edge pull request #59
Opened 2021-06-04 20:34 UTC by ygoyal18

When compiled with BYOC_MODE=ON, it will allow you to create a generic Pelion Edge LmP builds for your targets i.e., image is not associated to a Pelion DM account or a developer certificate. This looks similar to FACTORY_MODE but with this, you will not have to provision the gateway using pep or FCU/FCC tool. Once the gateway is booted, you will have to place the developer and update certificate C files at `/userdata/mbed`. The launch script will detect that and pass it through `edge-tool` to generate a CBOR fomatted credential object which will then be passed to `edge-core` on start. 

It also enable you to publish and distribute these images to other users who can use their own certificate without having to setup their own build environment. 

Added different service unit file for this mode and a launch script to go with it.

I have manually tested this flow. This PR should be merged after edge-tool has been added - #58.

2021-06-04 21:52 UTC, ryannowarm approved these changes

2021-06-07 06:05 UTC, esajaa requested changes

2021-06-07 06:05 UTC, esajaa commented on recipes-connectivity/mbed-edge-core/mbed-edge-core.inc
> +    ${@bb.utils.contains('MBED_EDGE_CORE_CONFIG_BYOC_MODE','OFF','file://edge-core.service','',d)} \
Would it make sense to have 'MBED_EDGE_CORE_CONFIG_DEVELOPER_MODE','ON' instead? That way each option would have one systemd service dedicated to them

2021-06-07 06:05 UTC, esajaa commented on recipes-connectivity/mbed-edge-core/mbed-edge-core.inc
> +        install -m 755 "${WORKDIR}/launch-byoc-edge-core.sh" "${D}${wbindir}/"
This script has run-time dependency (=RDEPENDS) to edge-tool

2021-06-07 06:11 UTC, esajaa commented on recipes-connectivity/mbed-edge-core/mbed-edge-core.inc
> +    ${@bb.utils.contains('MBED_EDGE_CORE_CONFIG_BYOC_MODE','OFF','file://edge-core.service','',d)} \
By each option I meang MBED_EDGE_CORE_CONFIG_DEVELOPER_MODE and MBED_EDGE_CORE_CONFIG_BYOC_MODE options

2021-06-07 15:20 UTC, petedyerarm commented on recipes-connectivity/mbed-edge-core/files/launch-byoc-edge-core.sh
> +if [[ ! -f "$DEV_CBOR" ]]; then
Depending on the resolution of the comment I left in PR #58 (run edge-tool on the host), this could be simplified to just checking for the DEV_CBOR file. 
Otherwise I think it is fine as is.

2021-06-07 17:05 UTC, ygoyal18 commented on recipes-connectivity/mbed-edge-core/mbed-edge-core.inc
> +    ${@bb.utils.contains('MBED_EDGE_CORE_CONFIG_BYOC_MODE','OFF','file://edge-core.service','',d)} \
@esajaa edge-core.service is needed for both DEV and FACTORY MODE. Do you suggest that we add two conditions explicitly defining that or this negative conditional statement will do?

2021-06-07 17:05 UTC, ygoyal18 commented on recipes-connectivity/mbed-edge-core/mbed-edge-core.inc
> +        install -m 755 "${WORKDIR}/launch-byoc-edge-core.sh" "${D}${wbindir}/"
Nice catch.. will add that.

2021-06-07 17:13 UTC, ygoyal18 commented on recipes-connectivity/mbed-edge-core/files/launch-byoc-edge-core.sh
> +if [[ ! -f "$DEV_CBOR" ]]; then
@petedyerarm Do you mean that if DEV_CBOR exists then start edge-core with cbor otherwise not?

2021-06-07 18:20 UTC, petedyerarm commented on recipes-connectivity/mbed-edge-core/files/launch-byoc-edge-core.sh
> +if [[ ! -f "$DEV_CBOR" ]]; then
No - what I meant was if you run edge-tool on the host and transfer just the CBOR file to the device then the script could be made simpler. Either start edge-core with cbor or don't start it at all.
But if you do have edge-tool on the device then this script can stay as it is.

2021-06-07 19:41 UTC, ygoyal18 commented on recipes-connectivity/mbed-edge-core/files/launch-byoc-edge-core.sh
> +if [[ ! -f "$DEV_CBOR" ]]; then
Okay ya that's what I meant. I think we want edge-tool on non-production gateways because that will be one less thing for users to worry about.

2021-06-08 05:30 UTC, esajaa commented on recipes-connectivity/mbed-edge-core/mbed-edge-core.inc
> +    ${@bb.utils.contains('MBED_EDGE_CORE_CONFIG_BYOC_MODE','OFF','file://edge-core.service','',d)} \
Ah, I misunderstood a bit. If it's required for both then forget this comment

2021-06-08 05:49 UTC, esajaa commented on recipes-connectivity/mbed-edge-core/mbed-edge-core.inc
> +    ${@bb.utils.contains('MBED_EDGE_CORE_CONFIG_BYOC_MODE','OFF','file://edge-core.service','',d)} \
Although, perhaps if it's possible to do an OR-comparison in the statement it'd be a bit clearer, but I'm not sure if the syntax allows that

2021-06-08 05:49 UTC, esajaa approved these changes

2021-06-08 06:37 UTC, merged